# Some basic Theano brain teasers
There is a n-dim tensor variable, you `dimshuffle` with pattern `x`, then you take its sum at some axis `y`, what do you get? Does it sound like a good puzzle to you? Then let's figure it out.

But first we should `import` some magics...

In [1]:
import theano
import numpy as np

from theano import tensor as T

### Custom tensor type 
It's very easy to define a new tensor type in Theano via the `broadcastable` argument.

In [2]:
dvector  = T.TensorType(broadcastable=(False,), dtype='float32')
drow     = T.TensorType(broadcastable=(True, False), dtype='float32')
dcol     = T.TensorType(broadcastable=(False, True), dtype='float32')
dtensor3 = T.TensorType(broadcastable=(False, False, False), dtype='float32')

### Reductions
If you do `foo(axis=n)` then the dimension `n` will be collapsed and deleted with all values in the new matrix equal to the sum of the corresponding collapsed values.

In [5]:
# new variable of type dtensor3
x = dtensor3()

# sum of x along axis 0
s0 = x.sum(axis=0)

# feed x some value 
x_val = np.reshape(np.arange(3 * 3 * 3, dtype='float32'),(3, 3, 3))
dic   = {x : x_val}

# s0 is the sum of 3 sub 3x3 matrix
print "x:\n{0}".format(x_val)
print "s0:\n{0}".format(s0.eval(dic))

x:
[[[  0.   1.   2.]
  [  3.   4.   5.]
  [  6.   7.   8.]]

 [[  9.  10.  11.]
  [ 12.  13.  14.]
  [ 15.  16.  17.]]

 [[ 18.  19.  20.]
  [ 21.  22.  23.]
  [ 24.  25.  26.]]]
s0:
[[ 27.  30.  33.]
 [ 36.  39.  42.]
 [ 45.  48.  51.]]


In [ ]:
# teaser 1, guess?
s1 = x.sum(axis=1)
s2 = x.sum(axis=0).sum(axis=0)
s3 = x.sum(axis=(0,1))
s4 = x.sum(axis=0).sum(axis=1)

# some common reductions
total = x.sum()
marginals = x.sum(axis=(0,1))
mx = x.max(axis=1)

### Dimshuffle
Now having some good understanding about the dimensions of Theano tensor, let's face the `dimshuffle` monster :-) Here we will examine our good friend `tensor3` (not too boring, not too hard)